# python test_rerun.py -t 'tt_one_fridge_pick' -f 'oracle'
python test_rerun.py -t 'tt_one_fridge_table_pick' -f 'oracle'
python test_rerun.py -t 'tt_one_fridge_table_in' -f 'oracle'
python test_rerun.py -t 'tt_two_fridge_pick' -f 'oracle'
python test_rerun.py -t 'tt_two_fridge_in' -f 'oracle'

# # python test_rerun.py -t 'tt_one_fridge_pick' -f 'None'
# python test_rerun.py -t 'tt_one_fridge_table_pick' -f 'None'
# python test_rerun.py -t 'tt_one_fridge_table_in' -f 'None'
# python test_rerun.py -t 'tt_two_fridge_pick' -f 'None'
# python test_rerun.py -t 'tt_two_fridge_in' -f 'None'