#!/bin/bash

# 0926 constrained placing
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 0 10 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 100 110 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 200 210 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 300 310 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 400 410 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 500 510 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 600 610 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 700 710 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 800 810 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 900 910 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'

sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 10 20 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 110 120 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 210 220 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 310 320 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 410 420 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 510 520 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 610 620 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 710 720 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 810 820 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 910 920 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'

sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 20 30 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 120 130 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 220 230 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 320 330 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 420 430 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 520 530 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 620 630 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 720 730 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 820 830 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 920 930 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'

sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 30 40 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 130 140 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 230 240 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 330 340 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 430 440 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 530 540 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 630 640 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 730 740 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 830 840 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 930 940 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'

sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 40 50 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 140 150 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 240 250 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 340 350 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 440 450 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 540 550 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 640 650 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 740 750 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 840 850 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'
sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 940 950 10 clean_dish_feg_collect_rollouts_cluster_0927.yaml'


# 0925_constrained_placing_parallel
# sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 0 100 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 100 200 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 200 300 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 300 400 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 400 500 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 500 600 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 600 700 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 700 800 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 800 900 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 900 1000 10 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'

# 0923_constrained_placing_parallel
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 0 99 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 100 199 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 200 299 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 300 399 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 400 499 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 500 599 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 600 699 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 700 799 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 800 899 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'
#sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh 900 999 0 9 clean_dish_feg_collect_rollouts_cluster_parallel_sink.yaml'

# 0923
# sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts.sh 0 99 0 10'
# sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts.sh 100 199 0 10'
# sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts.sh 200 299 0 10'
# sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts.sh 300 399 0 10'
# sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts.sh 400 499 0 10'
# sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts.sh 500 599 0 10'
# sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts.sh 600 699 0 10'

# sbatch start_sbatch_job.sh 'bash bash_scripts/cluster/collect_rollouts_parallel.sh'